FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY api/AuthApi/*.csproj ./
RUN dotnet restore
COPY api/AuthApi/ ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "AuthApi.dll"]